### ISSUE TITLE
Mardown caused error on post

### ISSUE THREAD

**Issue by amshali** [w7cook/OpenBook#217]
I removed it for now. But must be fixed. 

Template execution error (In /app/views/tags/post.html around line 21)
Execution error occured in template /app/views/tags/post.html. Exception raised was MissingMethodException : No signature of method: java.lang.String.markdown() is applicable for argument types: () values: [].

play.exceptions.TemplateExecutionException: No signature of method: java.lang.String.markdown() is applicable for argument types: () values: []
    at play.templates.BaseTemplate.throwException(BaseTemplate.java:86)
    at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:257)
    at play.templates.GroovyTemplate$ExecutableTemplate.invokeTag(GroovyTemplate.java:379)
    at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:232)
    at play.templates.Template.render(Template.java:26)
    at play.templates.GroovyTemplate.render(GroovyTemplate.java:187)
    at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
    at play.mvc.Controller.renderTemplate(Controller.java:660)
    at play.mvc.Controller.renderTemplate(Controller.java:640)
    at play.mvc.Controller.render(Controller.java:695)
    at controllers.Application.news(Application.java:25)
    at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
    at Invocation.HTTP Request(Play!)
Caused by: groovy.lang.MissingMethodException: No signature of method: java.lang.String.markdown() is applicable for argument types: () values: []
    at /app/views/tags/post.html.(line:21)
    at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:232)
    ... 15 more

**Comment by astolarz** [comment]
What were you doing at the time to cause this?

**Comment by amshali** [comment]
I started play and tried loading localhost:9000

**Comment by astolarz** [comment]
I didn't get any errors. Did you run 'play dependencies' before hand?

**Comment by amshali** [comment]
I did not. Maybe it was that. I reverted the changes. Did you committ your changes again ?

**Comment by ProCynic** [comment]
yeah, markdown requires a new module to work.

**Comment by astolarz** [comment]
I've added it back, and still haven't seen the error you got. Let me know if you see it come up again.

**Comment by amshali** [comment]
Okay, I'll try to test it.
