### ISSUE TITLE
Error setting profile photo

### ISSUE THREAD

**Issue by jtessler** [w7cook/OpenBook#228]
If you upload a photo, go to the set profile picture page, and then try to set it as profile picture, it fails...

```
Internal Server Error (500) for request GET /photos/setProfilePhoto?submit=Set
Execution exception (In /app/controllers/Photos.java around line 109)
IllegalArgumentException occured : id to load is required for loading

play.exceptions.JavaExecutionException: id to load is required for loading
       at play.mvc.ActionInvoker.invoke(ActionInvoker.java:231)
       at Invocation.HTTP Request(Play!)
Caused by: java.lang.IllegalArgumentException: id to load is required for loading
       at org.hibernate.event.LoadEvent.<init>(LoadEvent.java:89)
       at org.hibernate.event.LoadEvent.<init>(LoadEvent.java:61)
       at org.hibernate.impl.SessionImpl.get(SessionImpl.java:1002)
       at org.hibernate.impl.SessionImpl.get(SessionImpl.java:998)
       at org.hibernate.ejb.AbstractEntityManagerImpl.find(AbstractEntityManagerImpl.java:614)
       at org.hibernate.ejb.AbstractEntityManagerImpl.find(AbstractEntityManagerImpl.java:589)
       at play.db.jpa.JPQL.findById(JPQL.java:36)
       at models.Photo.findById(Photo.java)
       at controllers.Photos.setProfilePhoto(Photos.java:109)
       at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
       at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
       at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
       at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
       at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
       ... 1 more
```

**Comment by laurenyew** [comment]
Looks like Geoff overwrote my changes to photos. 
I had changed:
...#{if currentUser.equals(photo.owner)}
          ...#{form @Photos.setProfilePhoto(photo.id)}
            ...input type="submit" name="submit" class="btn" value=&{'photo.setAsProfilePhoto'} />...
          #{/form}
        #{/if}
to
:...a class = "button" href="@{Photos.setProfilePhoto(photo.id)}">...
      &{'photo.setAsProfilePhoto'}</a> <br>...
and it was changed back.
I'll try to fix this again.
